export default {
  C: ["cMajor", "cMinor"],
  D: ["dMajor", "dMinor"],
  E: ["eMajor", "eMinor"],
  F: ["fMajor", "fMinor"],
  G: ["gMajor", "gMinor"],
  A: ["aMajor", "aMinor"],
  B: ["bMajor", "bMinor"],
};

// export default {
//   C: [
//     "cMajor",
//     "cMinor",
//     "cMajor",
//     "cMinor",
//     "cMajor",
//     "cMinor",
//     "cMajor",
//     "cMinor",
//     "cMajor",
//     "cMinor",
//     "cMajor",
//     "cMinor",
//     "cMajor",
//     "cMinor",
//     "cMajor",
//     "cMinor",
//     "cMajor",
//     "cMinor",
//     "cMajor",
//     "cMinor",
//     "cMajor",
//     "cMinor",
//     "cMajor",
//     "cMinor",
//     "cMajor",
//     "cMinor",
//   ],
//   D: ["dMajor", "dMinor"],
//   E: ["eMajor", "eMinor"],
//   F: ["fMajor", "fMinor"],
//   G: ["gMajor", "gMinor"],
//   A: ["aMajor", "aMinor"],
//   B: ["bMajor", "bMinor"],
// };
