export default {
  C: ["cMajor", "cMinor", "cMajor7", "cMinor7", "cSus2", "cSus4"],
  CSharp: [
    "cSharpMajor",
    "cSharpMinor",
    "cSharpMajor7",
    "cSharpMinor7",
    "cSharpSus2",
    "cSharpSus4",
  ],
  D: ["dMajor", "dMinor", "dMajor7", "dMinor7", "dSus2", "dSus4"],
  DSharp: [
    "dSharpMajor",
    "dSharpMinor",
    "dSharpMajor7",
    "dSharpMinor7",
    "dSharpSus2",
    "dSharpSus4",
  ],
  E: ["eMajor", "eMinor", "eMajor7", "eMinor7", "eSus2", "eSus4"],
  F: ["fMajor", "fMinor", "fMajor7", "fMinor7", "fSus2", "fSus4"],
  FSharp: [
    "fSharpMajor",
    "fSharpMinor",
    "fSharpMajor7",
    "fSharpMinor7",
    "fSharpSus2",
    "fSharpSus4",
  ],
  G: ["gMajor", "gMinor", "gMajor7", "gMinor7", "gSus2", "gSus4"],
  GSharp: [
    "gSharpMajor",
    "gSharpMinor",
    "gSharpMajor7",
    "gSharpMinor7",
    "gSharpSus2",
    "gSharpSus4",
  ],
  A: ["aMajor", "aMinor", "aMajor7", "aMinor7", "aSus2", "aSus4"],
  ASharp: [
    "aSharpMajor",
    "aSharpMinor",
    "aSharpMajor7",
    "aSharpMinor7",
    "aSharpSus2",
    "aSharpSus4",
  ],
  B: ["bMajor", "bMinor", "bMajor7", "bMinor7", "bSus2", "bSus4"],
};
